---
abstract: 'Create a branch with fewer test files for faster development'
author:
  - 'James E Keenan (jkeenan@cpan.org)'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.141170'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Git-Reduce-Tests
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Cwd: '0'
  Data::Dumper: '0'
  File::Find: '0'
  Getopt::Long: '0'
  Git::Wrapper: '0.034'
  Test::Simple: '0.44'
  perl: '5.006'
version: '0.04'
